release using go releaser (#122)
* chore: add go releaser

* add go releaser

* chore: update command hook to use new binaries

* test: fix failing tests

* fix build version

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -1,40 +1,103 @@
-#!/bin/bash
+#!/bin/sh
 set -euo pipefail
 
-arch="$(arch)"
-arm=("arm armhf aarch64 aarch64_be armv6l armv7l armv8l arm64e") # arm64
-amd=("x86 x86pc i386 i686 i686-64 x64 x86_64 x86_64h athlon")    # amd64
-if [[ "${arm[*]}" =~ ${arch} ]]; then
-  arch="arm64"
-elif [[ "${amd[*]}" =~ ${arch} ]]; then
-  arch="amd64"
-elif [[ "${arch}" != "ppc64le" ]]; then
-  echo -e "ERROR: unsupported architecture \"${arch}\"" >&2
-  exit 2
-fi
+check_cmd() {
+  command -v "$1" > /dev/null 2>&1
+  return $?
+}
 
-plugin=${BUILDKITE_PLUGINS:-""}
-version=$(echo $plugin | sed -e 's/.*monorepo-diff-buildkite-plugin//' -e 's/\".*//')
-kernel=$(uname -s | awk '{print tolower($0)}')
-allowed=("linux darwin")
-if ! [[ "${allowed[*]}" =~ ${kernel} ]]; then
-  echo -e "ERROR: unsupported kernel \"${kernel}\"" >&2
-  exit 3
-fi
+say() {
+    local green=`tput setaf 2 2>/dev/null || echo ''`
+    local reset=`tput sgr0 2>/dev/null || echo ''`
+    echo "$1"
+}
 
-repo="https://github.com/monebag/monorepo-diff-buildkite-plugin"
-executable="monorepo-diff-buildkite-plugin-${kernel}-${arch}"
-test_mode="${BUILDKITE_PLUGIN_MONOREPO_DIFF_BUILDKITE_PLUGIN_TEST_MODE:-false}"
+err() {
+  local red=`tput setaf 1 2>/dev/null || echo ''`
+  local reset=`tput sgr0 2>/dev/null || echo ''`
+  say "${red}ERROR${reset}: $1" >&2
+  exit 1
+}
 
-if [ -z ${version} ]; then
-  url=${repo}/releases/latest/download/${executable}
-else
-  url=${repo}/releases/download/${version:1}/${executable}
-fi
+get_architecture() {
+  local _ostype="$(uname -s)"
+  local _cputype="$(uname -m)"
 
-if [[ "$test_mode" == "false" ]]; then
-  echo ${url}
-  curl -Lf -o ${executable} $url && chmod +x ${executable}
-fi
+  RETVAL="$_ostype"_"$_cputype"
+}
 
-./${executable}
+need_cmd() {
+  if ! check_cmd "$1"; then
+    err "need '$1' (command not found)"
+  fi
+}
+
+# This wraps curl or wget.
+# Try curl first, if not installed, use wget instead.
+downloader() {
+  if check_cmd curl; then
+    _dld=curl
+  elif check_cmd wget; then
+    _dld=wget
+  else
+    _dld='curl or wget' # to be used in error message of need_cmd
+  fi
+
+  if [ "$1" = --check ]; then
+    need_cmd "$_dld"
+  elif [ "$_dld" = curl ]; then
+    curl -sSfL "$1" -o "$2"
+  elif [ "$_dld" = wget ]; then
+    wget "$1" -O "$2"
+  else
+    err "Unknown downloader"
+  fi
+}
+
+get_version() {
+  local _plugin=${BUILDKITE_PLUGINS:-""}
+  local _version=$(echo $_plugin | sed -e 's/.*monorepo-diff-buildkite-plugin//' -e 's/\".*//')
+  RETVAL="$_version"
+}
+
+download_binary_and_run() {
+  get_architecture || return 1
+  local _arch="$RETVAL"
+
+  local _ext=""
+  case "$_arch" in
+    *windows*)
+      _ext=".exe"
+      ;;
+  esac
+
+  local _executable="monorepo-diff-buildkite-plugin"
+  local _repo="https://github.com/monebag/monorepo-diff-buildkite-plugin"
+
+  get_version || return 1
+  local _version="$RETVAL"
+
+  if [ -z ${_version} ]; then
+    _url=${_repo}/releases/latest/download/${_executable}_${_arch}${_ext}
+  else
+    _url=${_repo}/releases/download/${_version:1}/${_executable}_${_arch}${_ext}
+  fi
+
+  local test_mode="${BUILDKITE_PLUGIN_MONOREPO_DIFF_BUILDKITE_PLUGIN_TEST_MODE:-false}"
+
+  echo $_executable
+  if [[ "$test_mode" == "false" ]]; then
+    downloader "$_url" "$_executable"
+
+    if [ $? != 0 ]; then
+      say "failed to download $_url"
+      exit 1
+    fi
+
+    chmod +x ${_executable}
+  fi
+
+  ./${_executable}
+}
+
+download_binary_and_run "$@" || exit 1
