enhancement: make nice error messages for bad arch/kernel

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -8,6 +8,9 @@ if [[ "${arm[*]}" =~ ${arch} ]]; then
   arch="arm64"
 elif [[ "${amd[*]}" =~ ${arch} ]]; then
   arch="amd64"
+elif [[ "${arch}" != "ppc64le" ]]; then
+  echo -e "ERROR: unsupported architecture \"${arch}\"" >&2
+  exit 2
 fi
 
 plugin=${BUILDKITE_PLUGINS:-""}
@@ -15,7 +18,8 @@ version=$(echo $plugin | sed -e 's/.*monorepo-diff-buildkite-plugin//' -e 's/\".
 kernel=$(uname -s | awk '{print tolower($0)}')
 allowed=("linux darwin")
 if ! [[ "${allowed[*]}" =~ ${kernel} ]]; then
-  exit 1
+  echo -e "ERROR: unsupported kernel \"${kernel}\"" >&2
+  exit 3
 fi
 
 repo="https://github.com/chronotc/monorepo-diff-buildkite-plugin"
